version: '3.8'
services:
  jenkins:
    privileged: true
    user: root
    restart: on-failure:10
    image: jenkins/jenkins:latest
    container_name: my-jenkins
    ports:
      - 8099:8080
      - 50000:50000
    volumes:
      - /home/carlos/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock